-- 코드를 입력하세요
-- 0222년 01월 도서 판매 기록
-- 저자별 카테고리 별 매출액을 구함
-- 저자 ID, 저자명, 카테고리, 매출객(SALES) 출력
-- 저자 ID 오름차순, 카테고리 내림차순
SELECT I.AUTHOR_ID, I.AUTHOR_NAME, I.CATEGORY, SUM(I.PRICE * S.SALES) AS TOTAL_SALES
FROM BOOK_SALES S LEFT JOIN (SELECT A.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY, B.PRICE, B.BOOK_ID
                          FROM BOOK B LEFT JOIN AUTHOR A ON B.AUTHOR_ID = A.AUTHOR_ID) I
                  ON S.BOOK_ID = I.BOOK_ID
WHERE DATE_FORMAT(S.SALES_DATE, "%Y-%m") = "2022-01"
GROUP BY I.AUTHOR_ID, I.CATEGORY
ORDER BY I.AUTHOR_ID, I.CATEGORY DESC