-- 코드를 입력하세요
-- YEAR(), MONTH() 함수
-- SELECT 년, 월, 성별, COUNT(DISTINCT) AS USERS
-- GROUPY BY 년, 월, 성
-- ORDER BY 년, 월, 성
-- GENDER NULL CHECK
-- 제목 : 년, 월, 성별 별 상품 구매 회원 수 구하기

SELECT YEAR(SALE.SALES_DATE) AS YEAR, MONTH(SALE.SALES_DATE) AS MONTH, INFO.GENDER, COUNT(DISTINCT INFO.USER_ID)
FROM ONLINE_SALE SALE INNER JOIN USER_INFO INFO ON SALE.USER_ID = INFO.USER_ID
WHERE INFO.GENDER IS NOT NULL
GROUP BY YEAR, MONTH, INFO.GENDER
ORDER BY YEAR, MONTH, INFO.GENDER