-- 2022년 1월 카테고리 별 도서 판매량을 합산 GROUB BY CATEGORY
-- 카테고리, 총 판매량(TOTAL_SALES) 리스트를 출력
-- 카테고리로 오름차순 ORDER BY CATEGORY

SELECT B.CATEGORY, SUM(BS.SALES) AS TOTAL_SALES
FROM BOOK_SALES BS LEFT JOIN BOOK B ON BS.BOOK_ID = B.BOOK_ID
WHERE '202201' = DATE_FORMAT(BS.SALES_DATE,'%Y%m')
GROUP BY B.CATEGORY
ORDER BY B.CATEGORY