-- 코드를 입력하세요
SELECT MONTH(HIS.START_DATE) AS MONTH, HIS.CAR_ID, COUNT(*) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY  HIS 
INNER JOIN (SELECT CAR_ID, COUNT(*) AS CNT
           FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
           WHERE YEAR(START_DATE) = 2022
           AND MONTH(START_DATE) >= 8
           AND MONTH(START_DATE) <= 10
           GROUP BY CAR_ID) COUNT_HIS
ON HIS.CAR_ID = COUNT_HIS.CAR_ID
WHERE COUNT_HIS.CNT >= 5
AND YEAR(HIS.START_DATE) = 2022 
AND MONTH(HIS.START_DATE) >= 8
AND MONTH(HIS.START_DATE) <= 10
GROUP BY HIS.CAR_ID, MONTH
ORDER BY MONTH ASC, HIS.CAR_ID DESC