-- 코드를 입력하세요
-- 자동차 종류 == '세단'
-- 10월에 대여를 시작한 기록이 있는 자동차 리스트
-- 자동차 ID에 대한 중복은 없어야 함
-- 자동차 ID를 기준으로 내림 차순 ORDER BY ID DESC
SELECT CAR.CAR_ID
FROM CAR_RENTAL_COMPANY_CAR CAR LEFT JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY HIS ON CAR.CAR_ID = HIS.CAR_ID
WHERE CAR.CAR_TYPE = '세단' AND MONTH(HIS.START_DATE) = 10
GROUP BY CAR.CAR_ID
ORDER BY CAR.CAR_ID DESC