-- 코드를 입력하세요
-- ADDRESS LIKE 서울특별시%
-- SELECT ID, 이름, 종류, 즐겨찾기 수, 주소, 리뷰 평균 점수
-- 리뷰 평균 점수 소수점 세번째 자리에서 반올림 (2번째 자리까지)
-- ORDER BY 평균점수 DESC, 즐겨찾기 수 DESC


SELECT INFO.REST_ID, INFO.REST_NAME, INFO.FOOD_TYPE, INFO.FAVORITES, INFO.ADDRESS, ROUND(AVG(REVIEW.REVIEW_SCORE),2) AS SCORE
FROM REST_REVIEW REVIEW LEFT JOIN REST_INFO INFO ON REVIEW.REST_ID = INFO.REST_ID
WHERE INFO.ADDRESS LIKE "서울%"
GROUP BY INFO.REST_ID
ORDER BY SCORE DESC, INFO.FAVORITES DESC