-- 자동차 대여 기록 별 대여 금액 구하기
SELECT RENT_INFO.HISTORY_ID,
ROUND(RENT_INFO.DAILY_FEE * RENT_INFO.RENT_DAYS * (100 - IFNULL(PLAN.DISCOUNT_RATE,0)) / 100) AS FEE
FROM (SELECT HIS.HISTORY_ID, CAR.DAILY_FEE, DATEDIFF(END_DATE, START_DATE) + 1 AS RENT_DAYS,
      CASE 
        WHEN DATEDIFF(END_DATE, START_DATE) + 1 BETWEEN 7 AND 29 THEN '7일 이상'
        WHEN DATEDIFF(END_DATE, START_DATE) + 1 BETWEEN 30 AND 89 THEN '30일 이상'
        WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 90 THEN '90일 이상'
        ELSE NULL
      END AS DURATION_TYPE 
      FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY HIS LEFT JOIN CAR_RENTAL_COMPANY_CAR CAR
      ON HIS.CAR_ID = CAR.CAR_ID
      WHERE CAR.CAR_TYPE = '트럭') AS RENT_INFO
      LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN PLAN 
      ON RENT_INFO.DURATION_TYPE = PLAN.DURATION_TYPE AND PLAN.CAR_TYPE = '트럭'
ORDER BY FEE DESC, HIS.HISTORY_ID DESC